# Generated by Django 5.2.4 on 2025-08-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupaUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': '"auth"."users"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_num', models.CharField(max_length=6, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], default='client', max_length=20)),
                ('provider_type', models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], max_length=20, null=True)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('supabase_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.supauser')),
            ],
        ),
    ]
