# Generated by Django 5.2.4 on 2025-08-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provider_type',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('provider', 'Provider')], default='client', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_num',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
