# Generated by Django 5.2.4 on 2025-08-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_provider_type_profile_role_profile_user_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_num',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
