# Generated by Django 5.2.4 on 2025-08-12 01:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.CharField(max_length=6, unique=True)),
                ('payment_token', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on-the-way', 'On the way'), ('in-progress', 'In progress'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('service_type', models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], max_length=20)),
                ('job', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='users.profile')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_orders', to='users.profile')),
            ],
        ),
    ]
