# Generated by Django 5.2.4 on 2025-08-07 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_profile_supabase_id_alter_order_provider_and_more'),
        ('users', '0002_profile_provider_type_profile_role_profile_user_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_orders', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], max_length=20),
        ),
    ]
