# Generated by Django 5.2.4 on 2025-08-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_job_alter_order_client_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='job',
            field=models.CharField(max_length=30),
        ),
    ]
