[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "django-ninja>=1.4.3",
    "psycopg2-binary>=2.9.10",
    "python-decouple>=3.8",
    "uvicorn>=0.35.0",
]
